kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
clientConnection:
  kubeconfig: /config/kubeconfig.yaml
profiles:
  - schedulerName: cssa-scheduler
    plugins:
      score:
        enabled:
          - name: CSSA
    pluginConfig:
    - name: CSSA
      args:
        populationSize: 30
        maxIterations: 100
        
         